### ISSUE TITLE
Creating an offer should have an option that refuses escrow automatically

### ISSUE THREAD

**Issue by sebastien1234** [syscoin/syscoin1#117]
There should be an option when making an offer and not wishing to use escrow. This will be beneficial specially when companies setup their own blockmarket.

**Comment by sidhujag** [comment]
I think the consumer should always have the option of escrow to avoid incentive for bad vendors.. every vendor will remove escrow of this is implemented

**Comment by dwasyluk** [comment]
Just for some background this came up in today's team call- we were discussing volume use cases such as a large retailer wanting to use the SYS platform for selling goods but not wanting to have to deal with individual escrow operations/overhead (or even the possibility of it) on 1000s of items or more. 

I think the default should be optional escrow by default. If the seller chooses to disable the escrow option the buyer simply has the choice of not buying, or requesting the seller create a new offer (kinda like a custom listing) for them with escrow enabled. Either way it provides the additional flexibility that arguably puts larger retailers who may ask that same question of the platform mind's at ease. 

Because the buyer always has to use the SYS wallet in the end to complete the transaction (for now) we should display a very clear warning when escrow is disabled- something like **"WARNING: This seller has disabled Syscoin's built in escrow option ([more info](#)). Do not complete this purchase unless this is a trusted merchant, Syscoin's buyer protection is no longer active."**. Just a suggested warning, would replace the escrow checkbox and alias input if the offer is escrowEnabled = false.

**Comment by sidhujag** [comment]
This would benefit reputable arbiters... the consumer should really never not have the option because vendors will all disable it and consumers will have no choice because there is no competition rhat will offer it.. why would vendor want the overhead if they dont have to?

**Comment by sidhujag** [comment]
remember arbiter doesnt really get involved unless the consumer feels he does not get what he deserves for his money. there will be those losers that will always say they never got what they bought but how is rhat different than say a paypal dispute? infact paypal is worse because it blocks vendors entire account

**Comment by sebastien1234** [comment]
closing #117
