### ISSUE TITLE
Messaging is limited by pending operations on Alias?

### ISSUE THREAD

**Issue by sysmca** [syscoin/syscoin1#147]
Not sure if this is a bug or something that can't be resolved easily, but it seems I can't send a message while a previous message is confirming. This makes sending multiple messages using the same alias a lengthy process. I can imagine a busy vendor wanting to fire out dozens of messages one after the other.

**Comment by sidhujag** [comment]
Yes otherwise someone can send a message as someone else, you need to attach the alias output to the input of the message tx, this means that the new alias output won't be available until next block to use. This is necessitated by the need to have a "from" field. If we didn't need that we wouldn't have to do this.

**Comment by sidhujag** [comment]
I think this can be closed because if we open the limitation its not secure.
