### ISSUE TITLE
Certificate can be linked to two offers simultaneously

### ISSUE THREAD

**Issue by sysmca** [syscoin/syscoin1#155]
It's possible to assign the same certificate to two offers simultaneously. Surely once it's been linked it can't be linked again?

![same_cert_two_offers](https://cloud.githubusercontent.com/assets/15713199/13475474/08de3cd6-e0bb-11e5-8db1-ccb0eb42358f.jpg)

**Comment by sidhujag** [comment]
Yea this is possible, in general people buying cert offers will use escrow because you dont know if that cert is available or is even the right information that the buyer wants/needs. With escrow, the buyer will see the cert regardless of how many offers its used on. Offers with certs is first come first serve, so escrow is recommended to be used in this case for buyers.
