### ISSUE TITLE
Sold Items on market in Transactions

### ISSUE THREAD

**Issue by Snipsnoop** [syscoin/syscoin1#7]
Incoming Transactions from a sale at the marketplace should be somehow clearly noticeable as such.
Right now i receive a tx without any info if its send "just for fun" or via buy of a good and need to check offerinfo to see if one item was sold.
The info should be visible via listtransactions in 2 values, "OfferIdPayment" and "AmountGoodsBought"

(Submitted by JohnDorien1)

**Comment by Snipsnoop** [comment]
For some clarification this is from the seller perspective- if a user calls offerpay, the seller gets SYS accordingly but the TX in the transaction list does not clearly show it was from an offerpay and it can easily be confused as coming from another user as a direct payment.

(From Dan)

**Comment by dwasyluk** [comment]
Yeah this is a bit confusing from a seller perspective and could be more user friendly. Being that the wallet is a reference wallet though, I question if we have enough info on the client side to label this as an offer payment rather than simply a receive? Such as scanning offerinfo for an accept with a matching tx id or something along those lines. May inefficient but a suggestion nonetheless.

**Comment by sidhujag** [comment]
Changed the interface completely
