### ISSUE TITLE
Whitelist offer can still be purchased after owner has xferred cert permissing them to sell

### ISSUE THREAD

**Issue by dwasyluk** [syscoin/syscoin1#92]
1. Create an offer and add a cert to its whitelist and xfer that cert to your friend you want to be able to sell the offer.
2. You friend creates a resell offer, and then xfers the cert.
3. Your friend's friend creates a resell offer, and then xfers the cert 
   etc. etc.

This creates two problems: extends control out of the hands of the root seller by allowing multiple people to have valid, linked offers at the same time. It may also cause issues with refunding idk. When the reseller xfers the cert and there are linked offers that they are only permissed to resell because of that cert, those offers should be auto-expired. Only the current owner of the cert should be able to resell.

**Comment by sidhujag** [comment]
you can't control if the friend resells the cert as that is what the whitelists are for, if the reseller sells his cert to resell on your list then you can take him out of your whitelist and the reseller becomes invalid whoever controls it. What we can do is if a cert is being resold, it cant be resold again (latest push), so that if the cert was resold by the reseller it will not be resellable again.
